ivnas post about reproducibility
uzh-dqbm-cmi/lab-website pull request #45
Opened 2020-09-22 13:24 UTC by iivankovic

A quest for reproducible data science!

2020-09-22 15:17 UTC, lokijuhy requested changes
Love it! I went to see if you added a "reproducibility" tag, so we can make a series of these articles and have them be connected, and was delighted to see that you did! :) There's one tiny syntax error to make the tag work properly though.

2020-09-22 15:17 UTC, lokijuhy commented on content/post/about-reproducibility/index.md
> +- Reproducibility, Data Science
This is making one tag called "Reproducibility, Data Science". Put them in separate lines to make 2 tags.

2020-09-23 08:14 UTC, iivankovic commented on content/post/about-reproducibility/index.md
> +- Reproducibility, Data Science
Nice catch, fixed!

2020-09-23 12:42 UTC, lokijuhy approved these changes
💯

2020-09-23 12:47 UTC, merged