Add Publications
uzh-dqbm-cmi/lab-website pull request #79
Opened 2021-06-11 06:59 UTC by mcmahom5

2021-06-15 15:14 UTC, lokijuhy requested changes

2021-06-15 15:14 UTC, lokijuhy commented on content/publication/balazs-2021/cite.bib
> +@article{balazs2021,
This is the same paper as `content/publication/lymphoma-scRNA`. Should that one be deleted in favor of this updated one? (I noticed that when you click on the scRNA project page, it shows 2 papers: https://deploy-preview-79--goofy-bose-72cf26.netlify.app/project/single-cell-rna-sequencing/)

2021-06-15 15:14 UTC, lokijuhy commented on content/publication/nooralahzadeh-2021/index.md
> +authors: ["Farhad Nooralahzadeh", "Nicolas Perez Gonzalez", "Thomas Frauenfelder", "Koji Fujimoto", "Michael Krauthammer"]
In order to link paper authors with the person's bio page, put their name as written in the `authors/` directory here instead of the written out name. For example, putting `farhadzad` instead of "Farhad Nooralahzadeh" will make it so that the author links to the bio page, and that this paper is listed at the bottom of Farhad's bio page. You did this in the `zbalazs-2021` paper for Zsolt and Michael.

2021-06-15 15:14 UTC, lokijuhy commented on content/publication/schwarz-2020/cite.bib
> +      author={Kyriakos Schwarz and Ahmed Allam and Nicolas Andres Perez Gonzalez and Michael Krauthammer},
Same comment on the author names to make them link.

2021-06-15 15:43 UTC, mcmahom5 commented on content/publication/nooralahzadeh-2021/index.md
> +authors: ["Farhad Nooralahzadeh", "Nicolas Perez Gonzalez", "Thomas Frauenfelder", "Koji Fujimoto", "Michael Krauthammer"]
Done, thanks

2021-06-15 15:43 UTC, mcmahom5 commented on content/publication/schwarz-2020/cite.bib
> +      author={Kyriakos Schwarz and Ahmed Allam and Nicolas Andres Perez Gonzalez and Michael Krauthammer},
Done, thanks

2021-06-15 15:43 UTC, mcmahom5 commented on content/publication/balazs-2021/cite.bib
> +@article{balazs2021,
Yeah, I guess so. One was the preprint and this new one is the published version. I'll remove the older one

2021-06-16 07:51 UTC, lokijuhy approved these changes
🎉

2021-06-18 12:32 UTC, merged